### ISSUE TITLE
Error running CountMuts.py

### ISSUE THREAD

**Issue by AmiDay** [loeblab/Duplex-Sequencing#12]
Dear Loeb Lab,

I am trying to run the CountMuts.py script on my pileup file as produced by Samtools pileup and using the exact commands as indicated in the 2014 Nature Protocols publication. I am encountering the following errors each time:

Traceback (most recent call last):
  File "CountMuts.py", line 254, in <module>
    main()
  File "CountMuts.py", line 250, in main
    CountMutations(o, f, fOut)
  File "CountMuts.py", line 129, in CountMutations
    elif (float(linebins[4].count('N'))/(float(depth) + float(linebins[4].count('N')))) > o.n_cutoff:
ZeroDivisionError: float division by zero

I have tried changing the cut-off values for the % clonality and depth (e.g. -d 10 -C 0.1) and encounter the same error.

Can you suggest any solutions to this problem?

Many Thanks.

**Comment by mwschmit** [comment]
Hello,

Thank you for the message. This error can occur if you have no reads passing your cutoff parameters. Then, when the program divides by depth, it is dividing by 0.  Do you indeed have positions in your bam/pileup file that have  >10x depth? 

--Mike

**Comment by scottrk** [comment]
Closing as resolved.
