### ISSUE TITLE
ConsensusMaker.py 

### ISSUE THREAD

**Issue by zhangwl** [loeblab/Duplex-Sequencing#17]
Hi, 
I am running the SRR1799908.sra data down from NCBI. In the ConsensusMaker.py step, I am encountering the following errors each time.

Traceback (most recent call last):
  File "/home/jyc/zwl/soft/Duplex-Sequencing-master/ConsensusMaker.py", line 428, in <module>
    main()
  File "/home/jyc/zwl/soft/Duplex-Sequencing-master/ConsensusMaker.py", line 354, in main
    if (consensus.count("N" )/ len(consensus) <= o.Ncutoff and 'n' in o.filt) or ('n' not in o.filt):
ZeroDivisionError: integer division or modulo by zero

**Comment by scottrk** [comment]
Can you send me a the first few lines of one of your fastq files and a 
few lines from the input bam file. Also, can you send me a copy of the 
command you used to invoke ConsensusMaker.

Thanks,
Scott

**Comment by zhangwl** [comment]
first 4 lines of my fastq
@SRR1799908.1-HWI-7001239F_078:2:1101:1274:2240/1
GAGAGCCAAAAATGACTCGTACCCTGGGCACCCCCGGCAGTCCCAGCCTACCTTCAAGGTCTTCACGGCCACCGTCAGGCTGTATTTCTTCCACACGCCCT
+
^__eeeeegggfgiiiiiiihhiihiihhihhdgfghiiihiiiiiigggbccceeeddZ`bdbbbcccccccccccacccaabcdccdbcbcccc][_a_

1 line of SRR1799908.pe.sort.bam file
SRR1799908.1832630-HWI-7001239F_078:2:1202:7673:56664|CAAGGCGTAAAGCTCTCTTCCGGA  99  1   1841745 60  84M =   1841852191  TCCCACGTCAGCCTCCCACAGTGCTGGGATTATATGTGAGAGCCACCACGCCTGGCCCTGAATGTACTTTTATAATGTGACTTT    iiiiiiiiiiiiiiiiiiiiighiiiiigiiiiiiiiiiiiiiiiggggeeeeccddcccccccbcddedcccdddcbddcccc    XT:A:U  NM:i:0  SM:i:37 AM:i:37 X0:i:1  X1:i:0  XM:i:0  XO:i:0  XG:i:0  MD:Z:84

command line
[Uploading bash_my.bash.sh.txt…]()

command line of ConsensusMaker.py in bash file

# Step 5: Run Consensus Maker

echo "Starting Consensus Maker" | tee -a ${logFile}
date | tee -a ${logFile}

python ${DSpath}/ConsensusMaker.py --infile ${runIdentifier}.pe.sort.bam --tagfile ${runIdentifier}.pe.tagcounts --outfile ${runIdentifier}.sscs.bam --minmem $minMem --maxmem $maxMem --readlength $readLength --cutoff $cutOff --Ncutoff $nCutOff --read_type $readTypes --filt $filtersSet --isize $iSize

**Comment by scottrk** [comment]
Weird, I've never seen this error before. For some reason it thinks that 
the consensus length is 0. Can you try running it with the --filt option 
set to os instead of osn. Does it work?

Scott

**Comment by scottrk** [comment]
How about read 2. Does the first four lines of the fastq look like 
below? Can you post the first 4 lines of that?

Scott

**Comment by zhangwl** [comment]
first 4 lines of my fastq (read2)
@SRR1799908.1-HWI-7001239F_078:2:1101:1274:2240/2
TGTAAATCCTGCTGACTAGATGGAACGCACGGACATCACCATGAAGCACAAGCTGGGCGGGGGCCAGTACGGGGAGGTGTACGAGGGCGTGTGGAAGAAAT
+
_bbeeeeecggggiiiiiiihiiiiiihiihihiifhhiihiiiiiiiiiiihfhhiifcccccccc`bbcccccccQ^__bacccaacccaacbbccb^S

**Comment by scottrk** [comment]
I don't have a good explanation for this.  Can you post the entire shell script you're using?

**Comment by zhangwl** [comment]
#!/bin/bash

# DS bash script

# Version 2.1

# 

# Step 1: Setup variables for run:

clear

# Set up error checking

# Stop on any error

set -e

# Stop on an error inside a pipeline

set -o pipefail

# Throw an error on calling an unassigned variable

set -u

#DEFAULTS
DSpath='/home/jyc/zwl/soft/Duplex-Sequencing-master'
alignRef='/media/sf_01server/00-wanglab/zhangwl2/resources/b37/b37'
runIdentifier='dsSRR1799908'
read1in='/media/sf_01server/00-wanglab/zhangwl2/data/ds_data/head.SRR1799908_1.fq'
read2in='/media/sf_01server/00-wanglab/zhangwl2/data/ds_data/head.SRR1799908_2.fq'
iSize=-1
minMem=3
maxMem=1000
cutOff=0.7
nCutOff=1
readLength=0
barcodeLength=12
spacerLength=5
filtersSet='os'
readTypes='dpm'
repFilt=9
readOut=1000000

#NONDEFAULTS

#FINAL_READ_LENGTH
readLength=$((readLength-barcodeLength-spacerLength))

#LOG_FILE_NAME
logFile=${runIdentifier}.log.txt

#Export all variables
export DSpath
export alignRef
export runIdentifier
export read1in
export read2in
export iSize
export minMem
export maxMem
export cutOff
export nCutOff
export readLength
export barcodeLength
export spacerLength
export filtersSet
export readTypes
export repFilt
export readOut

# Print out options used to log file

touch $logFile
echo "Run identifier: " $runIdentifier | tee -a ${logFile}
echo "Program path: " $DSpath | tee -a ${logFile}
echo "Reference genome: " $alignRef | tee -a ${logFile}
echo "Barcode length: " $barcodeLength | tee -a ${logFile}
echo "Spacer length: " $spacerLength | tee -a ${logFile}
echo "Post-tag_to_header read length: " $readLength | tee -a ${logFile}
echo "Repetitive tag filter length: " $repFilt | tee -a ${logFile}
echo "Minimum family size: " $minMem | tee -a ${logFile}
echo "Maximum family size: " $maxMem | tee -a ${logFile}
echo "Consensus cutoff: " $cutOff | tee -a ${logFile}
echo "Consensus N cutoff: " $nCutOff | tee -a ${logFile}
echo "Read types: " $readTypes | tee -a ${logFile}
echo "Filters: " $filtersSet | tee -a ${logFile}
echo "" | tee -a ${logFile}

# Step 2: Run tag_to_header.py on imput files

echo "Starting Run" | tee -a ${logFile}
echo "tag_to_header starting"  | tee -a ${logFile}
date | tee -a ${logFile}
echo "" | tee -a ${logFile}

python ${DSpath}/tag_to_header.py --infile1 $read1in --infile2 $read2in --outfile1 ${runIdentifier}.seq1.fq.smi --outfile2 ${runIdentifier}.seq2.fq.smi --barcode_length $barcodeLength --spacer_length $spacerLength --read_out $readOut

# Step 3: Align sequences

echo "Aligning with BWA" | tee -a ${logFile}
date | tee -a ${logFile}

bwa aln $alignRef ${runIdentifier}.seq1.fq.smi > ${runIdentifier}.seq1.aln
bwa aln $alignRef ${runIdentifier}.seq2.fq.smi > ${runIdentifier}.seq2.aln
bwa sampe -s $alignRef ${runIdentifier}.seq1.aln ${runIdentifier}.seq2.aln ${runIdentifier}.seq1.fq.smi ${runIdentifier}.seq2.fq.smi > ${runIdentifier}.pe.sam

# Step 4: Sort aligned sequences

echo "Sorting aligned sequences" | tee -a ${logFile}
date | tee -a ${logFile}

samtools view -Sbu ${runIdentifier}.pe.sam | samtools sort - ${runIdentifier}.pe.sort

# Step 5: Run Consensus Maker

echo "Starting Consensus Maker" | tee -a ${logFile}
date | tee -a ${logFile}

python ${DSpath}/ConsensusMaker.py --infile ${runIdentifier}.pe.sort.bam --tagfile ${runIdentifier}.pe.tagcounts --outfile ${runIdentifier}.sscs.bam --minmem $minMem --maxmem $maxMem --readlength $readLength --cutoff $cutOff --Ncutoff $nCutOff --read_type $readTypes --filt $filtersSet --isize $iSize

# Step 6: Sort SSCSs

echo "Sorting SSCSs" | tee -a ${logFile}
date | tee -a ${logFile}

samtools view -bu ${runIdentifier}.sscs.bam | samtools sort - ${runIdentifier}.sscs.sort

# Step 7: Run Duplex Maker

echo "Starting Duplex Maker" | tee -a ${logFile}
date  | tee -a ${logFile}

python ${DSpath}/DuplexMaker.py --infile ${runIdentifier}.sscs.sort.bam --outfile ${runIdentifier}.dcs.bam --Ncutoff $nCutOff --readlength $readLength

# Step 8: Align DCSs

echo "Aligning DCSs" | tee -a ${logFile}
date | tee -a ${logFile}

bwa aln $alignRef ${runIdentifier}.dcs.r1.fq > ${runIdentifier}.dcs.r1.aln
bwa aln $alignRef ${runIdentifier}.dcs.r2.fq > ${runIdentifier}.dcs.r2.aln
bwa sampe -s $alignRef ${runIdentifier}.dcs.r1.aln ${runIdentifier}.dcs.r2.aln ${runIdentifier}.dcs.r1.fq ${runIdentifier}.dcs.r2.fq > ${runIdentifier}.dcs.sam

# Step 9: Sort aligned DCSs

echo "Sorting aligned DCSs" | tee -a ${logFile}
date | tee -a ${logFile}

samtools view -Sbu ${runIdentifier}.dcs.sam | samtools sort - ${runIdentifier}.dcs.aln.sort

# Step 10: Index sorted DCSs

echo "Indexing sorted DCSs" | tee -a ${logFile}
date | tee -a ${logFile}

samtools index ${runIdentifier}.dcs.aln.sort.bam

echo "Finished with run " $runIdentifier | tee -a ${logFile}
date | tee -a ${logFile}

**Comment by scottrk** [comment]
Ah, you have --readlength set to 0. That won't work since no read has a 
length of 0.  That would mean no read goes into making a consensus, 
which would lead to no consensus reads being made.  That would certainly 
lead to a division by zero error.  In this case, you want to set 
--readlength to 84.

**Comment by zhangwl** [comment]
oh, Ok, thank you!

**Comment by zhangwl** [comment]
oh, Ok, thank you!
