### ISSUE TITLE
mut-position.py

### ISSUE THREAD

**Issue by zhangwl** [loeblab/Duplex-Sequencing#19]
Hi, 
I am running the SRR1799911.sra data down from NCBI. After the mut-position.py step, I get the finally result of the data (file name: SRR1799911.dcs.d100-c0-0.001.mutpos). But it is difficult to understand the result file. Would you explain the mean of file? The first 5 lines of the file showed blow. Thank you!
1   G   169796677   104 0   0   0   0   0   0   0   0
1   C   169796678   106 0   0   0   0   0   0   0   0
1   T   169796679   108 0   0   0   0   0   0   0   0
1   G   169796680   109 0   0   0   0   0   0   0   0
1   A   169796681   108 0   0   0   0   0   0   0   0

**Comment by scottrk** [comment]
By field:

Chromosome name, reference base, reference position, depth, total # 
variants at that position, total T variants, total C variants, total G 
variants, total A variants, # insertions, # deletions, # undefined N's

Hope that helps.

**Comment by zhangwl** [comment]
OK, thank you for your help!

**Comment by scottrk** [comment]
Closing as resolved.
