### ISSUE TITLE
Where can I find file "read_1.fq", "read_2.fq" ??

### ISSUE THREAD

**Issue by lingbl** [loeblab/Duplex-Sequencing#21]
I'm a student, I'm reading the paper "Detecting ultralow-frequency mutations by  Duplex Sequencing", and try to re-do the "bioinformatic processing" in the paper.  
I have installed bwa, python in linux, but "tag_to_header.py" need file"read_1.fq" to run.  
Can you offer the fg files, then let me to run the program. Thx.

**Comment by scottrk** [comment]
I would suggest that you look in the "TestData" directory.  The 
accompanying README file in that directory will give you the URL to 
where the actual sequencing data is located.
