### ISSUE TITLE
consensus_maker.py not identifying first read in sorted BAM

### ISSUE THREAD

**Issue by noellenoyes** [loeblab/Duplex-Sequencing#39]
Every time I run Consensus_Maker.py script, it drops exactly 1 read from the sorted bam file.  When I went back to trace down this error using the tagcounts file and the corresponding sam file, I found that it always misses the first read in the (sorted) sam file (so, the first read in the corresponding sorted bam file as well).  I am not a strong python coder, so not sure where/why this is occurring, but I'm nearly positive it isn't my use of samtools view or sort in the intervening steps between bwa sampe and Consensus_Maker.py.

**Comment by scottrk** [comment]
Hmmm...interesting. There are going to be some big patches landing soon. 
Maybe those will fix this issue. I'll let you know when those land so 
you can test that out.

**Comment by scottrk** [comment]
Closing as resolved.
