### ISSUE TITLE
tag_to_header.py / alignment error

### ISSUE THREAD

**Issue by AmiDay** [loeblab/Duplex-Sequencing#4]
Dear loeblab,

I am following your duplex sequencing bioinformatics pipeline and have encountered an error once trying to align the output from the tag_to_header.py script.

At first, I got an error with the script because my read headers did not consist of a "/". However, I changed this so that a "\" would split the string right before the index sequence. For example:

initial read header:
@HWI-ST892:245:C41KRACXX:6:1101:1898:2153 1:N:0:CGATGTAT

new read header:
@HWI-ST892:245:C41KRACXX:6:1101:1898:2153 1:N:0/CGATGTAT

I then used these modified fastq files as input into the tag_to_header.py script and it seemed to work, generating the following output for the first read pair as an example (these are in separate files):

@HWI-ST892:245:C41KRACXX:6:1101:1898:2153_1:N:0|AAAAGCCGCGCC/CGATGTAT

@HWI-ST892:245:C41KRACXX:6:1101:1898:2153_2:N:0|AAAAGCCGCGCC/CGATGTAT

However, when I try to align the reads to create a SAM file using these files, I get the following error:

paired reads have different names: "HWI-ST892:245:C41KRACXX:6:1101:1898:2153_1:N:0|AAAAGCCGCGCC/CGATGTAT", "HWI-ST892:245:C41KRACXX:6:1101:1898:2153_2:N:0|AAAAGCCGCGCC/CGATGTAT"

However, when I align read pairs with different names without using the tag_to_header.py script, and using just the raw original fastq files, I do not encounter this error and the alignment proceeds without error.

Do you have any suggestions about why this isn't working? I would be very grateful.

Many Thanks.

**Comment by scottrk** [comment]
What software are you using to create the SAM file?

**Comment by AmiDay** [comment]
I am using BWA mem to create the SAM file. Although I do not think it is a problem with this, because I have used the same algorithm on the raw fastq files.
