### ISSUE TITLE
Is the code for corrected_qual_score correct line 230 ?

### ISSUE THREAD

**Issue by madsheilskov** [loeblab/Duplex-Sequencing#44]
The  line #230  in UnifiedConsensusMaker.py reads:
corrected_qual_score = map(lambda x: x if x < 41 else 41, qual_dict['ba:1'])

Should it have been (for second ba read ba:2):
corrected_qual_score = map(lambda x: x if x < 41 else 41, qual_dict['ba:2'])
?

**Comment by scottrk** [comment]
We will uploading a new version of Duplex-Seq shortly that fixes issues such as this. Closing in anticipation of upload. Please reopen if necessary.
