### ISSUE TITLE
Fastq file has read bases as N

### ISSUE THREAD

**Issue by abolia** [loeblab/Duplex-Sequencing#45]
Hi, 

I am running the UnifiedConsensusMaker.py on the unaligned bam file generated by Picard FastqToSam. 
 I used taglen as 3 becuase the UMI is the first three bases of the data read for both read 1 and read 2.  The actual data read starts at Base 6 for both read 1 and read 2 so I used the --spacerlen as 2. 

I used this command to run:
python ~/Git_Repos/Duplex-Sequencing/UnifiedConsensusMaker.py --input $name.unaligned.bam --prefix $name --taglen 3 --spacerlen 2

I get three outputs from running this command. First, a $name_temp.sort.bam file and 2 fastqs. My question is: Is this the bam file after collapsing? If so, I can see all the reads in this bam. However, my fastq 1 and 2 both have N's as the bases in my reads. Also their sizes are very small (~2015 reads), whereas my bam is pretty huge ~2.2 GB. Is there something that I am doing wrong. Can you please help me fix the issue.

Thank you.

**Comment by scottrk** [comment]
I strongly suspect that you don't have enough tag diversity. You only have, at best, a total of 4^6=2048 possible tag sequences. When consensus calling takes place it almost certainly grouping unrelated reads together which leads to high numbers of N's you're seeing.

**Comment by abolia** [comment]
Thanks for replying. Is there a work around this problem where it doesn't group unrelated reads. Ideally, it should only group reads that have same barcode and start. And shouldn't it print out all the singletons still as singletons?

Thank you.

**Comment by scottrk** [comment]
You'll want to use the version in the Nature Protocols paper which can be found in the folder of the same name.

**Comment by abolia** [comment]
Great. I will try that. 

Thank you.
