### ISSUE TITLE
How to account for upstream sample barcodes?

### ISSUE THREAD

**Issue by dcraig2** [loeblab/Duplex-Sequencing#46]
How would a region upstream of the random 12-nucleotide barcode be accounted for? e.g., sample barcodes. The following sequence is how I set it up:

5' *P5 region*, *Read 1*, *Sample Barcode*, *Universal Primer*, *Random Barcode*, *Spacer*, *TARGET SEQUENCE*, *Spacer*, *Random Barcode*, *Universal Primer*, *Sample Barcode*, Read 2*, *P7 region* 3'

In other words, I have 72 bases upstream of the *Random Barcode*

**Comment by scottrk** [comment]
There's code that parses out the sequences that form what you want to define as your tag. It uses simple string slicing.  You'd have to change that. That being said, it's not at all clear to me how your system would work, especially with the high number of invariant bases. The sequencer will choke on that. DS was designed based on the TruSeq adapter design. There's not any plans to support designs at this point.
