### ISSUE TITLE
Update docstring on tag_to_header.py to reflect new arguments

### ISSUE THREAD

**Issue by susinmotion** [loeblab/Duplex-Sequencing#49]
[tag_to_header.py](https://github.com/loeblab/Duplex-Sequencing/blob/ae37b27d2016b9736fd084d0d2b858e49de5a6d6/Nat_Protocols_Version/tag_to_header.py) docstring still references `--outfile1 `and `--outfile2` 
should be `--outprefix`

**Comment by scottrk** [comment]
We will be uploading a new version of this shortly that fixes a huge number of issues. Closing in anticipation of upload.
