### ISSUE TITLE
ConsensusMaker.py error

### ISSUE THREAD

**Issue by yanglq-bio** [loeblab/Duplex-Sequencing#51]
HI，I'm following the pipline to do the analysis,but when I running ConsensusMaker.py ,there always an error:
ConsensusMaker.py: error: argument --tag_file is required

I can't understand it ,I clearly set this parameter，Why does this error occur?the tag_file is not an output_file ?

**Comment by scottrk** [comment]
I need for info. What was the exact command you used and what was the exact error that was given. Also, I would suggest using the UnifiedConsensusCaller.py. It’s way faster and easier to use.

**Comment by yanglq-bio** [comment]
thanks for your reply.
my code is :
python ConsensusMaker.py --infile PE_reads.sort.bam --tagfile PE_reads.tagcounts --outfile SSCS.bam --min 3 --max 1000 --cutoff 0.7 --Ncutoff 0.3 --readlength 138
 --read_type dpm --filt osn
and the error is:
ConsensusMaker.py: error: argument --tag_file is required


In addition，UnifiedConsensusCaller.py is same to ConsensusMaker.py?





At 2018-04-23 21:57:26, "S. Kennedy" <notifications@github.com> wrote:
I need for info. What was the exact command you used and what was the exact error that was given. Also, I would suggest using the UnifiedConsensusCaller.py. It’s way faster and easier to use.

**Comment by scottrk** [comment]
There’s a mismatch between what you wrote and the error. Try using —tag_file instead since that’s what the error says. 

Yes and no. It takes raw fastq files and calls the consensuses without going through alignment, etc. it’s way faster and gives pretty much the same results.

**Comment by yanglq-bio** [comment]
thank you,I will try it.






At 2018-04-24 22:40:28, "S. Kennedy" <notifications@github.com> wrote:
There’s a mismatch between what you wrote and the error. Try using —tag_file instead since that’s what the error says.

Yes and no. It takes raw fastq files and calls the consensuses without going through alignment, etc. it’s way faster and gives pretty much the same results.

**Comment by scottrk** [comment]
Closing as resolved.
