### ISSUE TITLE
ConsensusMaker.py for Python3

### ISSUE THREAD

**Issue by ni6o6** [loeblab/Duplex-Sequencing#55]
Thanks for very useful codes.
I changed two parts of ConsensusMaker.py to run on Python3.
I will tell you about those two. 
1)
xrange --> range
2) 
line286
read_window = [bam_entry.__next__(), '']  # Get the first read

**Comment by scottrk** [comment]
We have updated Duplex-Seq scripts to be Python3 compatible and will be uploading a new version of the pipeline shortly. Closing issue in anticipation of upload.
